# -*- coding: utf-8 -*-
"""MusicApp

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tYTLmrFIkApXmahciEMhr6xWpO0gicW0
"""

def upload_and_play():
    print("Simulating file upload. Please imagine music is playing.")

def stop_music():
    print("Simulating music stop.")

def pause_music():
    print("Simulating music pause.")

def resume_music():
    print("Simulating music resume.")

# Main Menu
def music_player():
    while True:
        print("\nMusic Player Options:")
        print("1. Upload and Play Music")
        print("2. Pause Music")
        print("3. Resume Music")
        print("4. Stop Music")
        print("5. Exit")
        choice = input("Enter your choice (1-5): ")

        if choice == '1':
            upload_and_play()
        elif choice == '2':
            pause_music()
        elif choice == '3':
            resume_music()
        elif choice == '4':
            stop_music()
        elif choice == '5':
            print("Exiting Music Player. Goodbye!")
            break
        else:
            print("Invalid choice. Please try again.")

# Run the simulation
music_player()